Homework 4
kheyfetsdan/AndroidAcademyTest pull request #4
Opened 2020-12-06 18:40 UTC by kheyfetsdan

2020-12-07 20:55 UTC, phansier requested changes
Не всё досмотрел.
Завтра соберу проект и посмотрю код для Recycler-ов

2020-12-07 20:55 UTC, phansier commented on app/src/main/res/layout/view_holder_actor.xml
> +        android:layout_marginTop="7dp"
Лучше сделать 8dp

2020-12-07 20:55 UTC, phansier commented on app/src/main/res/layout/fragment_movies_details.xml
> +        <!--<ImageView
лучше убрать неиспользуемый код
если пригодится - можно восстановить по истории гита

2020-12-07 20:55 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/Movies.kt
> +    val poster: Drawable?,
лучше вместо Drawable использовать @DrawableRes Int
Drawable - резолвится в рантайме в зависимости от темы, например
а ResId будет более постоянным

2020-12-07 20:55 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/DataUtil.kt
> +            Movies(tenet_poster, "Telnet", tenet_tag, tenet_review, tenet_star, tenet_duration),
почему Telnet остался не строкой?)

2020-12-07 20:55 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/DataUtil.kt
> +    fun generateMoviesList(context: Context?): List<Movies> {
т.к. это твоя функция - лучше сразу сказать, что она принимает ненулабельный контекст, чтобы внутри не приходилось каждый раз его проверять на null
тем более, что ты используешь !!. вместо ?. - может привести к крашам в рантайме, если кто-то будет использовать твой метод вслепую (не смотря в имлементацию)

2020-12-07 20:55 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/DataUtil.kt
> +    fun generateActorsList(context: Context?): List<Actors> {
и тут тоже заменить на ненулабельный контекст

2020-12-07 20:55 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/DataUtil.kt
> +class DataUtil {
можно вместо class сделать object

2020-12-07 20:55 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/Actors.kt
> +    val photo: Drawable?,
тоже DrawableRes

2020-12-07 20:55 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/ActorsViewHolder.kt
> +    private val actor_name: TextView = itemView.findViewById(R.id.actor_name)
в коде лучше вместо kebab_case использовать camelCase

2020-12-07 20:55 UTC, phansier commented on app/src/main/res/drawable/rating_fill.xml
> +        android:drawable="@drawable/star_on_png"/>
вместо png можно попробовать векторные иконки

2020-12-07 20:55 UTC, phansier commented on app/src/main/res/drawable/rating_fill.xml
> +        android:state_window_focused="true"
зачем везде android:state_window_focused?

2020-12-09 13:07 UTC, phansier requested changes
В целом норм, есть что улучшить по замечаниям и верстке.

2020-12-09 13:07 UTC, phansier commented on app/src/main/res/layout/fragment_movies_list.xml
>              app:layout_constraintTop_toTopOf="@id/toolbar" />
Обращай внимание на ворнинги Android Studio
У ConstraintLayout нужно заменить layout_height

2020-12-09 13:07 UTC, phansier commented on app/src/main/res/layout/view_holder_actor.xml
> +    <ImageView
This view is not constrained vertically: at runtime it will jump to the top unless you add a vertical constraint

2020-12-09 13:07 UTC, phansier commented on app/src/main/res/layout/view_holder_actor.xml
> +        android:text="@string/downey"
лучше заменить android:text и app:srcCompat на tool:

2020-12-09 13:07 UTC, phansier commented on app/src/main/res/layout/view_holder_actor.xml
> +        android:layout_marginStart="16dp"
последний элемент не отступает от края экрана
можно либо добавить recyclerView дополнительный маргин справа (плохой вариант)
либо потренироваться с ItemDecoration - чтобы он не применял маргин к первому и последнему элементу

2020-12-09 13:07 UTC, phansier commented on app/src/main/res/layout/fragment_movies_details.xml
> +        <androidx.recyclerview.widget.RecyclerView
можно еще отдельные звезды заменить на новый RatingBar

2020-12-09 13:07 UTC, phansier commented on app/src/main/res/layout/fragment_movies_details.xml
> +            android:id="@+id/actor_recycler"
можно добавить
```
tools:listitem="@layout/view_holder_actor"
tools:orientation="horizontal"
```
чтобы представлять как выглядит recycler в превью

2020-12-09 13:07 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/ActorAdapter.kt
> +) : RecyclerView.Adapter<ActorsViewHolder>() {
проще унаследоваться от готового ListAdapter<List<Actors>,ActorsViewHolder>()

2020-12-09 13:07 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/ActorAdapter.kt
> +            listenerActor!!.onItemClick()
лучше поменять на ?.

2020-12-09 13:07 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/ActorAdapter.kt
> +            listenerActor!!.onItemClick()
Сейчас падает при нажатии

2020-12-09 13:07 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/MoviesAdapter.kt
> +class MoviesAdapter(
те же комменты, что и у ActorAdapter

2020-12-09 13:07 UTC, phansier commented on settings.gradle
> +include ':RatingBarSvg-master'
что это и зачем?)

2020-12-09 13:07 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/MoviesViewHolder.kt
> +    fun bind(movies: Movies) {
лучше Movies и Actors переименовать в единственное число

2020-12-09 13:07 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/ItemOffsetDecoration.kt
> +class ItemOffsetDecoration(private var mItemOffset: Int) : RecyclerView.ItemDecoration() {
в Java обычно используют нотацию  c m- или s- (это про mItemOffset)
в Kotlin обычно так не пишут

2020-12-09 13:07 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/FragmentMoviesList.kt
> +        val movies = DataUtil.generateMoviesList()
функцию generateMoviesList() можно заменить на 
```
val generateMoviesList: List<Movies> by lazy { ...}
```

2020-12-09 13:07 UTC, phansier commented on .idea/gradle.xml
> +            <option value="$PROJECT_DIR$/RatingBarSvg-master" />
как будто ты недокоммитил RatingBarSvg-master

2020-12-20 18:43 UTC, kheyfetsdan commented on settings.gradle
> +include ':RatingBarSvg-master'
Да я пытался чужой рейтинг бар затащить, чтобы с вектором работал, не получилось, модуль отключил, а это забыл убрать)

2020-12-20 18:43 UTC, kheyfetsdan commented on app/src/main/java/com/example/android/androidacademytest/FragmentMoviesList.kt
> +        val movies = DataUtil.generateMoviesList()
Я правильно понимаю, это нужно сделать, чтобы потом с многопоточность лучше работало?

2020-12-20 18:44 UTC, kheyfetsdan commented on app/src/main/java/com/example/android/androidacademytest/ActorAdapter.kt
> +) : RecyclerView.Adapter<ActorsViewHolder>() {
Не понял зачем, да и не завелось это у меня, для чего это нужно?

2020-12-20 18:47 UTC, kheyfetsdan commented on app/src/main/res/layout/view_holder_actor.xml
> +        android:layout_marginStart="16dp"
Не знаю правильно ли я тебя понял или нет, но тут сделал чтобы маргина не было у первого элемента, так как там маргин ресайклера задан и если маргин айтему добавлять, то будет лишний отступ. У последнего маргиналии добавил

2020-12-21 15:18 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/ActorAdapter.kt
> +) : RecyclerView.Adapter<ActorsViewHolder>() {
тебе не нужно будет самому делать список и управлять им

2020-12-21 15:19 UTC, phansier commented on app/src/main/java/com/example/android/androidacademytest/FragmentMoviesList.kt
> +        val movies = DataUtil.generateMoviesList()
не совсем. просто у тебя этот список будет существовать только в единственном экземпляре и создастся тогда, когда будет нужен

2020-12-21 16:03 UTC, phansier commented on app/src/main/res/layout/view_holder_actor.xml
> +        android:layout_marginStart="16dp"
Отправил скриншот в телеграме, что я имел ввиду

2020-12-21 16:06 UTC, phansier commented on settings.gradle
> +include ':RatingBarSvg-master'
Я так и понял)

2020-12-21 16:09 UTC, phansier commented on app/src/main/res/drawable/rating_fill.xml
> +        android:drawable="@drawable/star_on_png"/>
Не пробовал?

2020-12-21 16:13 UTC, phansier commented
Выглядит ок, кроме расположения ресайклеров.

2020-12-21 16:13 UTC, phansier approved these changes

2021-01-16 14:58 UTC, merged